GET http://localhost:8000/api/books
###

POST http://localhost:8000/api/login

Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "asdasd123"
}

###
GET http://localhost:8000/api/users'

###
PUT  http://localhost:8000/api/updateLoan/1
Content-Type: application/json

{
    "status": "finish"
}